name: {{name.snakeCase()}}
description: {{description}}}
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  # State Managers and Service Locators
  provider: any
  get_it: any

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: any
  
  # Remote Api Client
  apex_api: any

  # Object Equality Comparisons
  equatable: any

  # Linking and sharing
  url_launcher: any
  share_plus: any

  # Toast and Notification Management
  bot_toast: any

  # Storage and Data Persistent
  shared_preferences: any

  # Routing and Navigation
  auto_route: any

  # Icons
  flutter_feather_icons: any

  # I/O
  file_picker: any
  image_picker: any
  path_provider: any

  # Date & Time
  shamsi_date: any
  persian_datetime_picker: any

  # UI | Theme | Styling
  shimmer: any
  data_table_2: any
  tab_indicator_styler: any
  flex_color_scheme: any
  auto_size_text: any
  device_preview: any

  # Image
  flutter_svg: any

  # Animations
  animate_do: any
  loading_animation_widget: any

  # Device
  fingerprintjs: any
  platform_device_id: any

  # Utility
  quiver: any
  intersperse: any
  collection: any
  decimal: any
  universal_html: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  lint: any
  dart_code_metrics: any
  
  # Generators
  auto_route_generator: any
  build_runner: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/audio/
    - assets/raw/

  # fonts:
  #   - family: FontFamily
  #     fonts:
  #       - asset: fonts/Regular.ttf
  #       - asset: fonts/Bold.ttf
  #       weight: 700

flutter_intl:
  enable: true
